@isTest
private class bxt_test_number_to_letter
{
    @isTest static void testNumber()
    {
    String a = bxt_number_to_letter.number_letter(501000.89);
    String b = bxt_number_to_letter.number_letter(1001.89);
    String C = bxt_number_to_letter.number_letter(1000120.89);
    String d = bxt_number_to_letter.number_letter(975000114.89);
    String e = bxt_number_to_letter.number_letter(100.89);
    String f = bxt_number_to_letter.number_letter(230780.89);
    String g = bxt_number_to_letter.number_letter(176.89);
    String h = bxt_number_to_letter.number_letter(1001000.89);
    String i = bxt_number_to_letter.number_letter(74.89);
    String j = bxt_number_to_letter.number_letter(50.89);
    String k = bxt_number_to_letter.number_letter(1234789.89);
    String l = bxt_number_to_letter.number_letter(123001789.89);
    String m = bxt_number_to_letter.number_letter(123456789.89);
    }
}